CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome_completo VARCHAR(255) NOT NULL,
	data_nascimento DATE NOT NULL,
	email VARCHAR(255) NOT NULL,
	telefone VARCHAR(50),
	senha VARCHAR(128) NOT NULL,
	imagem_perfil VARCHAR(512),
	ativo BOOLEAN DEFAULT true NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);
